require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable

# Styles

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: true
  Exclude:
    - lib/tasks/payments_context/merchants/import_data.rake

# RSpec

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - spec/lib/tasks/**/*

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Exclude:
    - spec/support/shared_contexts/rake.rb

RSpec/ContextWording:
  Enabled: true
  Exclude:
    - spec/support/shared_contexts/rake.rb
